### PR TITLE
Update rollMap.js

### PR DESCRIPTION
**Pull request by jaredthedewg**
Added blizzard world to rollmap command

### CODE REVIEW

**Comment by joshramsbottom** [comment]
Not sure yet about how to decide when to add new maps, do we just want to mirror the competitive map list? or OWL? or vsgaming?

**Comment by jaredthedewg** [comment]
I think adding them as soon as blizz adds them. People need to learn the map as well as strats. Might as well add it here :|

**Comment by hjlinde** [comment]
agreed, don't think there should be any relation with OWL or VSG. pugs exist for learning and having fun - might as well add new maps as soon as they go live.

**Comment by joshramsbottom** [comment]
Merging (#3) over this one because the list was also organised according to game type.

**Pull request closed without merging**
